# Exercício 1
**Inspecionando um Array NumPy**

Um objeto numpy possui atributos e métodos, herdados da classe (numpy.ndarray). Crie um array  e inspecione os seguintes atributos:

shape: uma tupla que contém o número de elementos (tamanho) em cada dimensão do array;

size: número total de elementos do array;

ndim: número de dimensões (eixos);

nbytes: número de bytes utilizado no armazenamento dos dados;

dtype: data type dos elementos do array.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7])

print('Shape:', array.shape)
print('Size:', array.size)
print('Eixos:', array.ndim)
print('Bytes:', array.nbytes)
print('Tipo:', array.dtype)

Shape: (7,)
Size: 7
Eixos: 1
Bytes: 56
Tipo: int64


# Exercício 2

Com base no exercício anterior crie uma função que receba um array e mostre na tela seus atributos. Verifique se o argumento inserido é de fato um objeto numpy. Use também a função built-in type() para verificar a classe do objeto.

```
Retorno esperado:

inspecionar_array(np.array([1,2,3]))
 
Shape : (3,)
Size:  3
Ndim:  1
Nbytes:  24
Dtype:  int64
Type:  <class 'numpy.ndarray'>

array([1, 2, 3, 4])

inspecionar_array([1,2,3])
 
'O objeto inserido não é um array NumPy.'
```

In [ ]:
def inspecionar_array(a):
  if isinstance(a,np.ndarray):
    print('Shape:', a.shape)
    print('Size:', a.size)
    print('Eixos:', a.ndim)
    print('Bytes', a.nbytes)
    print('Tipo:', a.dtype)
    print('Tipo:', type(a))
    return a
  else:
    return 'O objeto inserido não é um array NumPy.'


array = np.array([1,2,3,4,5,6,7,8,9,10])
lista = [1,2,3,4,5,6]

inspecionar_array(array)
inspecionar_array(lista)

Shape: (10,)
Size: 10
Eixos: 1
Bytes 80
Tipo: int64
Tipo: <class 'numpy.ndarray'>


'O objeto inserido não é um array NumPy.'

# Exercício 3

Use a função np.array() para criar os arrays unidimensionais listados abaixo:

```
a) Use uma lista como argumento e obtenha:

array([-1,  4,  7,  9])



b) Use a função range() e obtenha:
    
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



c)Use uma tupla como argumento e obtenha:
    
array([10, 11, 12, 13, 14])


d) Use a função range() e obtenha:
    
array([1990, 1995, 2000, 2005, 2010, 2015, 2020])



e) Use a função range() e obtenha:

array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])


f) Obtenha:

array(100)
```

In [ ]:
def funcaoNpArray(a):
  return print(np.array(a))

# Letra a)
vetor = np.array(range(-2,11))
index = [0,2,3,4,5,7,8,10,12]
funcaoNpArray(np.delete(vetor, index))

# Letra b)
funcaoNpArray(range(1,11))

# Letra c)
tupla = (10,11,12,13,14)
funcaoNpArray(tupla)

# Letra d)
funcaoNpArray(range(1990,2021,5))

# Letra e)
funcaoNpArray(range(2020,1899,-10))

# Letra f)
funcaoNpArray(100)

[-1  4  7  9]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14]
[1990 1995 2000 2005 2010 2015 2020]
[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]
100


# Exercício 4

A função np.ones() permite criar um array preenchido com o número 1 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array. Use esta função para criar os arrays a seguir:

```
a) array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

b) array([[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]])

c) array([[1, 1],
          [1, 1],
          [1, 1]])
```

In [ ]:
# Letra a)
tenNumbersOne = np.ones(10)
print(tenLines)

# Letra b)
matrix1 = np.ones(shape=(4,4))
print(matrix1)

# Letra c)
matrix2 = np.ones(shape=(3,2), dtype=int)
print(matrix2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1]
 [1 1]
 [1 1]]


# Exercício 5

A função np.zeros() permite criar um array preenchido com o número 0 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array (default é o float). Use esta função para criar os arrays a seguir:

```
a) array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


b) array([[0., 0.],
         [0., 0.]])  
       

c) array([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]])

```

In [ ]:
# Letra a)
tenNumbersZero = np.zeros(10)
print(tenNumbersZero)

# Letra b)
matrix1 = np.zeros(shape=(2,2))
print(matrix1)

# Letra c)
matrix2 = np.zeros(shape=(4,6))
print(matrix2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Exercício 6

Crie os arrays a seguir:

```
a) array([[10],
         [15],
         [20],
         [25],
         [30],
         [35],
         [40],
         [45]])

b) array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])

c) array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
          [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
          [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
          [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
          [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])
       
Dica: use np.arange() ou np.array(range()).
```

In [ ]:
# Letra a)
matrix1 = np.arange(10,46,5).reshape(-1,1)
print(matrix1)

# Letra b)
matrix2 = np.arange(-50,-4, 5)
print(matrix2)

# Letra c)
matrix3 = np.arange(50,150, 2).reshape(-1,10)
print(matrix3)


[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]
[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]
[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]


# Exercício 7

Utilize a função np.full(shape, fill_value, dtype) para criar os arrays a seguir. Esta função permite criar um array com um shape e dtype definidos pelo usuário, preenchido com um determinado valor.

```
a) array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

b) array([[-5., -5., -5., -5.],
         [-5., -5., -5., -5.],
         [-5., -5., -5., -5.],
         [-5., -5., -5., -5.]])

c) array([[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]])

d) array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])
```

Dica: outra possibilidade seria obter os arrays com uma operação diferente, a partir da multiplicação de uma matriz preenchida com número 1 por um determinado valor.


In [ ]:
# Letra a)
matrix1 = np.full(shape=10,fill_value=5.0)
print(matrix1)

# Letra b)
matrix2 = np.full(shape=(5,5),fill_value=-5.0)
print(matrix2)

# Letra c)
matrix3 = np.full(shape=(10,10),fill_value=50)
print(matrix3)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[[-5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5.]]
[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]


# Exercício 8

Defina o array K e verifique se há dados ausentes (missing data). Use a função np.isnan().
```
array([[ nan,   1.,  10.,   0.],
       [ nan,  nan,  nan,  nan],
       [100.,  50.,  nan, -25.],
       [ 30.,  nan,  nan, 130.]])
```

In [ ]:
k = np.array([[ np.nan,   1.,  10.,   0.],
           [ np.nan,  np.nan,  np.nan,  np.nan],
           [100.,  50.,  np.nan, -25.],
           [ 30.,  np.nan,  np.nan, 130.]])

print(np.isnan(k))

[[ True False False False]
 [ True  True  True  True]
 [False False  True False]
 [False  True  True False]]


# Exercício 9

A função np.linspace() retorna um array com números contendo espaçamento uniforme em um intervalo definido. Crie um array com números dentro do intervalo [1,21] em 5 partes.

Retorno esperado:

array([ 1.,  6., 11., 16., 21.])

In [ ]:
array = np.linspace(1,21,5)
print(array)

[ 1.  6. 11. 16. 21.]


# Exercício 10

A função np.logspace() retorna números com espaçamento uniforme em uma escala logarítmica. Crie um array com números dentro do intervalo [1,51] em 10 partes com a função np.logspace().

Retorno esperado:

```
array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])
```

In [ ]:
A = np.logspace(1,51,10).reshape(-1,1)
print(A)

[[1.00000000e+01]
 [3.59381366e+06]
 [1.29154967e+12]
 [4.64158883e+17]
 [1.66810054e+23]
 [5.99484250e+28]
 [2.15443469e+34]
 [7.74263683e+39]
 [2.78255940e+45]
 [1.00000000e+51]]


# Exercício 11

Use a função np.diag() para construir o array a seguir:

```
array([[ 5,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0, 30]])
```

In [ ]:
matrix = np.diag(np.arange(5,31,5))
print(matrix)

[[ 5  0  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0  0 25  0]
 [ 0  0  0  0  0 30]]


# Exercício 12

Use a função np.eye() (ou ainda np.identity()) para obter o array seguir.

```
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])
```

Dica: essa matriz é definida como matriz identidade, neste caso de ordem 10, e assume grande relevância em diversos cálculos computacionais, como veremos mais adiante.

In [ ]:
matrix = np.eye(10)
print(matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# Exercício 14

Obtenha a soma dos elementos de cada array a seguir. Use a função np.sum(). Implemente uma solução com loop for, para tanto armazene os vetores em uma lista.

```
import numpy as np
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))

Retorno esperado:

Soma dos elementos do array 1:  55
Soma dos elementos do array 2:  255.0
Soma dos elementos do array 3:  1275
Soma dos elementos do array 4:  10056552148.564463
Soma dos elementos do array 5:  105

```

In [ ]:
# Sem o loop for
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))

def soma(array,num):
  total = np.sum(array)
  print(f'Soma dos elementos do array {num}: {total}')

soma(array1,1)
soma(array2,2)
soma(array3,3)
soma(array4,4)
soma(array5,5)

 


Soma dos elementos do array 1: 55
Soma dos elementos do array 2: 255.0
Soma dos elementos do array 3: 1275
Soma dos elementos do array 4: 10056552148.564463
Soma dos elementos do array 5: 105


In [ ]:
# Com o loop for
array1 = np.arange(1, 11)
array2 = np.linspace(1, 50, 10)
array3 = np.array(range(51))
array4 = np.logspace(1, 10, 5)
array5 = np.diag(range(5, 31, 5))

arrays = [array1, array2, array3, array4, array5]
for index, array in enumerate(arrays, start=1):
    print(f'Soma dos elementos do array {index}: ', array.sum())

Soma dos elementos do array 1:  55
Soma dos elementos do array 2:  255.0
Soma dos elementos do array 3:  1275
Soma dos elementos do array 4:  10056552148.564463
Soma dos elementos do array 5:  105


# Exercício 15

A partir da matriz definida abaixo obtenha: 

a) soma total dos elementos; 

b) soma das linhas ; 

c) soma das colunas.

```
import numpy as np
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)
```

In [ ]:
np.random.seed(1)
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)

# Letra a)
print('Soma total dos elementos: ', matriz.sum())

# Letra b)
print('Soma das linhas: ', matriz.sum(axis = 1))

# Letra c)
print('Soma das colunas: ', matriz.sum(axis = 0))


Soma total dos elementos:  613
Soma das linhas:  [124  92 162 151  84]
Soma das colunas:  [137 257 219]


# Exercício 16

Obtenha o valor máximo e o valor mínimo de cada array abaixo. Implemente uma solução com loop for.

```
import numpy as np
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))


Dica: para obter o valor máximo e mínimo de um array podemos usar array.max() e array.min() ( ou ainda max(array) e min(array)).
```

In [ ]:
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))

arrays = [array1,array2,array3,array4]

for index,array in enumerate(arrays, start=1):
    print(f'Array {index}')
    print(f'Valor máximo: ', array.max())
    print(f'Valor mínimo: ', array.min())
    print()

Array 1
Valor máximo:  27
Valor mínimo:  -1

Array 2
Valor máximo:  280
Valor mínimo:  -88

Array 3
Valor máximo:  1.0188743111221994
Valor mínimo:  -1.7841494619227805

Array 4
Valor máximo:  50
Valor mínimo:  12



# Exercício 17

Crie uma função que receba uma matriz como entrada e calcule:

    a) Valor máximo da matriz;

    b) Valor máximo por coluna;

    c) Valor máximo por linha;

    d) Valor mínimo da matriz;

    e) Valor mínimo por coluna;

    f) Valor mínimo por linha.


Exemplo de retorno para a matriz definida abaixo:

```   
Input:

matriz = np.random.randint(-1000,1000,50).reshape(10,5)
info_matriz(matriz)

Output:

Valor máximo da matriz:  987
Valor máximo por coluna:  [959 987 597 748 719]
Valor máximo por linha:  [ 987  312  982  204  719  689  101  793 -460  959]
Valor mínimo da matriz:  -969
Valor mínimo por coluna:  [-878 -966 -969 -884 -881]
Valor mínimo por linha:  [  30 -878 -335 -863  -40 -289 -660 -239 -969 -966]
```


In [ ]:
# Sem a condicional if 

np.random.seed(2)
matriz = np.random.randint(-1000,1000,50).reshape(10,5)

def info_matriz(matriz):
  a = matriz.max() # Letra a)
  b = matriz.max(axis=0) # Letra b)
  c = matriz.max(axis=1) # Letra c)
  d = matriz.min() # Letra d)
  e = matriz.min(axis=0) # Letra e)
  f = matriz.min(axis=1) # Letra f)
  resultados = []
  resultados.extend([a,b,c,d,e,f])
  return print(f'Valor máximo da matriz: {resultados[0]} \n Valor máximo por coluna: {resultados[1]} \n Valor máximo por linha: {resultados[2]} \n Valor mínimo da matriz: {resultados[3]} \n Valor mínimo por coluna: {resultados[4]} \n Valor mínimo por linha: {resultados[5]}')

info_matriz(matriz)

Valor máximo da matriz: 732 
 Valor máximo por coluna: [326 652 616 608 732] 
 Valor máximo por linha: [ 608  287 -275  311  652  126  594  732  478  616] 
 Valor mínimo da matriz: -969 
 Valor mínimo por coluna: [-969 -567 -507 -640 -949] 
 Valor mínimo por linha: [-507 -701 -567 -596 -876 -949 -641 -745 -879 -969]


In [ ]:
# Com a condicional if

np.random.seed(2)
def info_matrix(matrix):
    
    if isinstance(matrix,np.ndarray) and matrix.ndim == 2:
        print(f'Valor máximo da matriz: ', matrix.max())
        print(f'Valor máximo por coluna: ', matrix.max(axis = 0))
        print(f'Valor máximo por linha: ', matrix.max(axis = 1))
        print(f'Valor mínimo da matriz: ', matrix.min())
        print(f'Valor mínimo por coluna: ', matrix.min(axis = 0))
        print(f'Valor mínimo por linha: ', matrix.min(axis =1))
    else:
        return None
    
if __name__=='__main__':
    matrix = np.random.randint(-1000,1000,50).reshape(10,5)
    info_matrix(matrix)


Valor máximo da matriz:  732
Valor máximo por coluna:  [326 652 616 608 732]
Valor máximo por linha:  [ 608  287 -275  311  652  126  594  732  478  616]
Valor mínimo da matriz:  -969
Valor mínimo por coluna:  [-969 -567 -507 -640 -949]
Valor mínimo por linha:  [-507 -701 -567 -596 -876 -949 -641 -745 -879 -969]


# Exercício 18

Com base no array definido abaixo obtenha sua média, mediana, variância e desvio padrão.

```
import numpy as np
arr = np.random.normal(40,0.5,size = (300))
```

Dica:

Média: np.mean();

Mediana: np.median();

Desvio padrão: np.std();

Variância: np.var().

In [ ]:
np.random.seed(1)
arr = np.random.normal(40,0.5,size = (300))
print(f'Média: {np.mean(arr)}')
print(f'Mediana: {np.median(arr)}')
print(f'Desvio Padrão: {np.std(arr)}')
print(f'Variância: {np.var(arr)}')

Média: 40.03719992074308
Mediana: 40.044088047041136
Desvio Padrão: 0.47192162527153914
Variância: 0.222710020398931


# Exercício 19

Com base nos arrays definidos a seguir obtenha a matriz de covariância e a matriz de correlação.

```
import numpy as np
x = np.random.rand(100)
y = np.random.uniform(size=100)
```

Dica: use np.corrcoef() e np.cov().

In [ ]:
x = np.random.rand(100)
y = np.random.uniform(size=100)

print(f'Matriz de covariância do array x: {np.corrcoef(x)}')
print(f'Matriz de correlação do array x: {np.cov(x)}')
print()
print(f'Matriz de covariância do array y: {np.corrcoef(y)}')
print(f'Matriz de correlação do array y: {np.cov(y)}')

Matriz de covariância do array x: 1.0
Matriz de correlação do array x: 0.08550649047080368

Matriz de covariância do array y: 1.0
Matriz de correlação do array y: 0.07475780727963469


# Exercício 20

Obtenha o índice do valor máximo do array A.

```
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])
```

Dica: use np.argmax() ou array.argmax().

In [ ]:
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])

print(f'O número do índice que tem o valor máximo do array A é: {np.argmax(A)}')

O número do índice que tem o valor máximo do array A é: 9


# Exercício 21

Obtenha o índice do valor mínimo do array B.

```
B = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])
```

Dica: use np.argmin() ou array.argmin().

In [ ]:
B = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])

print(f'O número do índice que tem o valor máximo do array B é: {np.argmax(B)}')

O número do índice que tem o valor máximo do array B é: 9


# Exercício 22

Escreva uma função que receba um array NumPy e mostre na tela um conjunto de  estatísticas descritivas deste objeto.

Resultado esperado:

``` 
Input

array = np.array([-57, 101, 270, 130, 144])
info_array(array)


Output:

Valor máximo: 270
Valor mínimo: -57
Média: 117.6
Mediana: 130.0
Variância: 10967.439999999999
Desvio padrão: 104.72554607162475
```


In [ ]:
array = np.array([-57, 101, 270, 130, 144])

def info_array(array):
  if isinstance(array,np.ndarray):
    print(f'Valor máximo: {np.max(array)}')
    print(f'Valor mínimo: {np.min(array)}')
    print(f'Média: {np.mean(array)}')
    print(f'Mediana: {np.median(array)}')
    print(f'Variância: {np.var(array)}')
    print(f'Desvio padrão: {np.std(array)}')
  else:
    return None

info_array(array)


Valor máximo: 270
Valor mínimo: -57
Média: 117.6
Mediana: 130.0
Variância: 10967.439999999999
Desvio padrão: 104.72554607162475


# Exercício 23

Use a função np.unique() para obter um array com os elementos únicos do array abaixo. Para tanto, armazene o novo array em uma variável.

```
A = np.array([
    [1, 3, 3, 4, 5],
    [4, 7, 11, 3, 5],
    [1, 11, 4, 4, 11]])
```

In [ ]:
A = np.array([
    [1, 3, 3, 4, 5],
    [4, 7, 11, 3, 5],
    [1, 11, 4, 4, 11]])

B = np.unique(A)
print(B)

[ 1  3  4  5  7 11]


# Exercício 24

Indexação de arrays 1-D

Considerando os arrays abaixo:

```
import numpy as np
array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])
```

Obtenha:

a) o primeiro, o terceiro e o último elemento de cada array;

b) inverta o array;

c) pegue o número 20 em ambos os arrays e armazene a soma em uma variável.

In [ ]:
# Sem a estrutura de repetição for

array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])

# Letra a)
print('Array 1:')
print(f'Primeiro elemento: {array1[0]}')
print(f'Segundo elemento: {array1[2]}')
print(f'Último elemento: {array1[-1]}')
print()
print('Array 2:')
print(f'Primeiro elemento: {array2[0]}')
print(f'Segundo elemento: {array2[2]}')
print(f'Último elemento: {array2[-1]}')

print()

# Letra b)
print('Array 1:')
print(array1[::-1])
print()
print('Array 2:')
print(array2[::-1])

print()

# Letra c)

sum = array1[1]+array2[6]
print(sum)

Array 1:
Primeiro elemento: 10
Segundo elemento: 30
Último elemento: 40

Array 2:
Primeiro elemento: 100
Segundo elemento: 5
Último elemento: 170

Array 1:
[40 30 20 10]

Array 2:
[170 155 130  20 100  40   1   5  30 100]

40


In [ ]:
# Com a estrutura de repetição for

array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])
arrays = [array1,array2]

for index,array in enumerate(arrays,start=1):
  print(f'{index}º array')
  print(f'Primeiro elemento: {array[0]}')
  print(f'Terceiro elemento: {array[2]}')
  print(f'Último elemento: {array[-1]}')
  print(f'Inversão: {array[::-1]}')
  print()

sum = array1[1]+array2[6]
print(sum)


1º array
Primeiro elemento: 10
Terceiro elemento: 30
Último elemento: 40
Inversão: [40 30 20 10]

2º array
Primeiro elemento: 100
Terceiro elemento: 5
Último elemento: 170
Inversão: [170 155 130  20 100  40   1   5  30 100]

40


# Exercício 25

Indexação de arrays 2-D

Acesse os números 9 e 90 do array abaixo.

```
import numpy as np
ar = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])
```

In [ ]:
ar = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])
print(ar[0,-2])
print(ar[1,-2])

9
90


# Exercício 2

Indexação de arrays 3-D

Acesse os números 5, 9, 3 e 21 do array abaixo.

```
import numpy as np
ar = np.array([
    [[1, 1, 5, 1],
     [1, 1, 1, 9]],
    [[1, 3, 1, 1],
     [1, 1, 21, 1]]])
```

In [ ]:
ar = np.array([
    [[1, 1, 5, 1],
     [1, 1, 1, 9]],
    [[1, 3, 1, 1],
     [1, 1, 21, 1]]])

print(ar[0,0,2])
print(ar[0,1,3])
print(ar[1,0,1])
print(ar[1,1,2])

5
9
3
21


# Exercício 27

Slicing 1-D

Com base no array abaixo obtenha o slice do índice 2 até o índice 6.

```
import numpy as np
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
```

Dica: Em Python, slicing significa que podemos selecionar elementos entre índices especificados. Sintaxe: [start:end:pass].

Se não especificarmos o start o valor default será 0. Se não definirmos o step, será considerado o valor 1.

In [ ]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ar[2:7]

array([3, 4, 5, 6, 7])