# Exercício 1
**Inspecionando um Array NumPy**

Um objeto numpy possui atributos e métodos, herdados da classe (numpy.ndarray). Crie um array  e inspecione os seguintes atributos:

shape: uma tupla que contém o número de elementos (tamanho) em cada dimensão do array;

size: número total de elementos do array;

ndim: número de dimensões (eixos);

nbytes: número de bytes utilizado no armazenamento dos dados;

dtype: data type dos elementos do array.

In [2]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7])

print('Shape:', array.shape)
print('Size:', array.size)
print('Eixos:', array.ndim)
print('Bytes:', array.nbytes)
print('Tipo:', array.dtype)

Shape: (7,)
Size: 7
Eixos: 1
Bytes: 56
Tipo: int64


# Exercício 2

Com base no exercício anterior crie uma função que receba um array e mostre na tela seus atributos. Verifique se o argumento inserido é de fato um objeto numpy. Use também a função built-in type() para verificar a classe do objeto.


---


Retorno esperado:

inspecionar_array(np.array([1,2,3]))
 
Shape : (3,)

Size:  3

Ndim:  1

Nbytes:  24

Dtype:  int64

Type:  <class 'numpy.ndarray'>

array([1, 2, 3, 4])


inspecionar_array([1,2,3])
 
'O objeto inserido não é um array NumPy.'

In [ ]:
def inspecionar_array(a):
  if isinstance(a,np.ndarray):
    print('Shape:', a.shape)
    print('Size:', a.size)
    print('Eixos:', a.ndim)
    print('Bytes', a.nbytes)
    print('Tipo:', a.dtype)
    print('Tipo:', type(a))
    return a
  else:
    return 'O objeto inserido não é um array NumPy.'


array = np.array([1,2,3,4,5,6,7,8,9,10])
lista = [1,2,3,4,5,6]

inspecionar_array(array)
inspecionar_array(lista)

Shape: (10,)
Size: 10
Eixos: 1
Bytes 80
Tipo: int64
Tipo: <class 'numpy.ndarray'>


'O objeto inserido não é um array NumPy.'

# Exercício 3

Use a função np.array() para criar os arrays unidimensionais listados abaixo:

a) Use uma lista como argumento e obtenha:

array([-1,  4,  7,  9])

---

b) Use a função range() e obtenha:
    
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---

c)Use uma tupla como argumento e obtenha:
    
array([10, 11, 12, 13, 14])

---

d) Use a função range() e obtenha:
    
array([1990, 1995, 2000, 2005, 2010, 2015, 2020])

---

e) Use a função range() e obtenha:

array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])

---

f) Obtenha:

array(100)

In [ ]:
def funcaoNpArray(a):
  return print(np.array(a))

# Letra a)
vetor = np.array(range(-2,11))
index = [0,2,3,4,5,7,8,10,12]
funcaoNpArray(np.delete(vetor, index))

# Letra b)
funcaoNpArray(range(1,11))

# Letra c)
tupla = (10,11,12,13,14)
funcaoNpArray(tupla)

# Letra d)
funcaoNpArray(range(1990,2021,5))

# Letra e)
funcaoNpArray(range(2020,1899,-10))

# Letra f)
funcaoNpArray(100)

[-1  4  7  9]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14]
[1990 1995 2000 2005 2010 2015 2020]
[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]
100


# Exercício 4

A função np.ones() permite criar um array preenchido com o número 1 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array. Use esta função para criar os arrays a seguir:

```
a) array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

b) array([[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]])

c) array([[1, 1],
          [1, 1],
          [1, 1]])
```

In [ ]:
# Letra a)
tenNumbersOne = np.ones(10)
print(tenLines)

# Letra b)
matrix1 = np.ones(shape=(4,4))
print(matrix1)

# Letra c)
matrix2 = np.ones(shape=(3,2), dtype=int)
print(matrix2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1]
 [1 1]
 [1 1]]


# Exercício 5

A função np.zeros() permite criar um array preenchido com o número 0 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array (default é o float). Use esta função para criar os arrays a seguir:

```
a) array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


b) array([[0., 0.],
         [0., 0.]])  
       

c) array([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]])

```

In [ ]:
# Letra a)
tenNumbersZero = np.zeros(10)
print(tenNumbersZero)

# Letra b)
matrix1 = np.zeros(shape=(2,2))
print(matrix1)

# Letra c)
matrix2 = np.zeros(shape=(4,6))
print(matrix2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Exercício 6

Crie os arrays a seguir:

```
a) array([[10],
         [15],
         [20],
         [25],
         [30],
         [35],
         [40],
         [45]])

b) array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])

c) array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
          [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
          [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
          [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
          [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])
       
Dica: use np.arange() ou np.array(range()).
```

In [ ]:
# Letra a)
matrix1 = np.arange(10,46,5).reshape(-1,1)
print(matrix1)

# Letra b)
matrix2 = np.arange(-50,-4, 5)
print(matrix2)

# Letra c)
matrix3 = np.arange(50,150, 2).reshape(-1,10)
print(matrix3)


[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]
[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]
[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]


# Exercício 7

Utilize a função np.full(shape, fill_value, dtype) para criar os arrays a seguir. Esta função permite criar um array com um shape e dtype definidos pelo usuário, preenchido com um determinado valor.

```
a) array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

b) array([[-5., -5., -5., -5.],
         [-5., -5., -5., -5.],
         [-5., -5., -5., -5.],
         [-5., -5., -5., -5.]])

c) array([[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]])

d) array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
         [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])
```

Dica: outra possibilidade seria obter os arrays com uma operação diferente, a partir da multiplicação de uma matriz preenchida com número 1 por um determinado valor.


In [ ]:
# Letra a)
matrix1 = np.full(shape=10,fill_value=5.0)
print(matrix1)

# Letra b)
matrix2 = np.full(shape=(5,5),fill_value=-5.0)
print(matrix2)

# Letra c)
matrix3 = np.full(shape=(10,10),fill_value=50)
print(matrix3)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[[-5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5.]]
[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]


# Exercício 8

Defina o array K e verifique se há dados ausentes (missing data). Use a função np.isnan().
```
array([[ nan,   1.,  10.,   0.],
       [ nan,  nan,  nan,  nan],
       [100.,  50.,  nan, -25.],
       [ 30.,  nan,  nan, 130.]])
```

In [18]:
k = np.array([[ np.nan,   1.,  10.,   0.],
           [ np.nan,  np.nan,  np.nan,  np.nan],
           [100.,  50.,  np.nan, -25.],
           [ 30.,  np.nan,  np.nan, 130.]])

print(np.isnan(k))

[[ True False False False]
 [ True  True  True  True]
 [False False  True False]
 [False  True  True False]]


# Exercício 9

A função np.linspace() retorna um array com números contendo espaçamento uniforme em um intervalo definido. Crie um array com números dentro do intervalo [1,21] em 5 partes.

Retorno esperado:

array([ 1.,  6., 11., 16., 21.])

In [20]:
array = np.linspace(1,21,5)
print(array)

[ 1.  6. 11. 16. 21.]


# Exercício 10

A função np.logspace() retorna números com espaçamento uniforme em uma escala logarítmica. Crie um array com números dentro do intervalo [1,51] em 10 partes com a função np.logspace().

Retorno esperado:

```
array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])
```

In [36]:
A = np.logspace(1,51,10).reshape(-1,1)
print(A)

[[1.00000000e+01]
 [3.59381366e+06]
 [1.29154967e+12]
 [4.64158883e+17]
 [1.66810054e+23]
 [5.99484250e+28]
 [2.15443469e+34]
 [7.74263683e+39]
 [2.78255940e+45]
 [1.00000000e+51]]
