# Exercício 1
**Inspecionando um Array NumPy**

Um objeto numpy possui atributos e métodos, herdados da classe (numpy.ndarray). Crie um array  e inspecione os seguintes atributos:

shape: uma tupla que contém o número de elementos (tamanho) em cada dimensão do array;

size: número total de elementos do array;

ndim: número de dimensões (eixos);

nbytes: número de bytes utilizado no armazenamento dos dados;

dtype: data type dos elementos do array.

In [30]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7])

print('Shape:', array.shape)
print('Size:', array.size)
print('Eixos:', array.ndim)
print('Bytes:', array.nbytes)
print('Tipo:', array.dtype)

Shape: (7,)
Size: 7
Eixos: 1
Bytes: 56
Tipo: int64


# Exercício 2

Com base no exercício anterior crie uma função que receba um array e mostre na tela seus atributos. Verifique se o argumento inserido é de fato um objeto numpy. Use também a função built-in type() para verificar a classe do objeto.


---


Retorno esperado:

inspecionar_array(np.array([1,2,3]))
 
Shape : (3,)

Size:  3

Ndim:  1

Nbytes:  24

Dtype:  int64

Type:  <class 'numpy.ndarray'>

array([1, 2, 3, 4])


inspecionar_array([1,2,3])
 
'O objeto inserido não é um array NumPy.'

In [31]:
def inspecionar_array(a):
  if isinstance(a,np.ndarray):
    print('Shape:', a.shape)
    print('Size:', a.size)
    print('Eixos:', a.ndim)
    print('Bytes', a.nbytes)
    print('Tipo:', a.dtype)
    print('Tipo:', type(a))
    return a
  else:
    return 'O objeto inserido não é um array NumPy.'


array = np.array([1,2,3,4,5,6,7,8,9,10])
lista = [1,2,3,4,5,6]

inspecionar_array(array)
inspecionar_array(lista)

Shape: (10,)
Size: 10
Eixos: 1
Bytes 80
Tipo: int64
Tipo: <class 'numpy.ndarray'>


'O objeto inserido não é um array NumPy.'

# Exercício 3

Use a função np.array() para criar os arrays unidimensionais listados abaixo:

a) Use uma lista como argumento e obtenha:

array([-1,  4,  7,  9])

---

b) Use a função range() e obtenha:
    
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---

c)Use uma tupla como argumento e obtenha:
    
array([10, 11, 12, 13, 14])

---

d) Use a função range() e obtenha:
    
array([1990, 1995, 2000, 2005, 2010, 2015, 2020])

---

e) Use a função range() e obtenha:

array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])

---

f) Obtenha:

array(100)

In [48]:
def funcaoNpArray(a):
  return print(np.array(a))

# Letra a)
vetor = np.array(range(-2,11))
index = [0,2,3,4,5,7,8,10,12]
funcaoNpArray(np.delete(vetor, index))

# Letra b)
funcaoRange = np.array(range(1,11))


# Letra c)

tupla = np.array((10,11,12,13,14))










[-1  4  7  9]
